services:
  backend: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ..:/workspaces
      - ./backend/:/app:z
      - ./logs/:/logs
      - ./data/tmp:/data
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    # ports:
    #   - '8000:8000'
    command: /start
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_data:/backups
    env_file:
      - .envs/.local/.postgres

  frontend:
    image: node:22.12.0-bookworm-slim
    user: 1000:1000
    working_dir: /app
    volumes:
      - ./mydb/frontend:/app
    command: yarn dev

  # Servidor Web NGINX
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      # Arquivo de configuração do Ngnix para este ambiente.
      - ./mydb/compose/local/nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      # Diretório onde o backend manipula arquivos, e que deve ficar acessivel ao servidor web.
      - ./data/tmp:/var/www/data
    depends_on:
      - backend
      - frontend
