services:
  backend: &django
    image: linea/target:backend_teste
    volumes:
      - ./data/tmp:/data
      - .logs:/logs
      # Django SAML
      - ./certificates:/app/config/certificates
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: /start

  frontend:
    image: linea/target:frontend_teste
    depends_on:
      - backend

  postgres:
    image: docker.io/postgres:14
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_data:/backups
    env_file:
      - .env

  redis:
    image: docker.io/redis:6
    volumes:
      - ./data/redis:/data

  nginx:
    image: nginx:latest
    ports:
      - 8188:80
    volumes:
      # Arquivo de configuração do Ngnix para este ambiente.
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      # Diretório onde o backend manipula arquivos, e que deve ficar acessivel ao servidor web.
      - ./data/tmp:/var/www/data
    depends_on:
      - backend
      - frontend
